# Server Configuration
server.port=8282

# Application Name
spring.application.name=api-gateway

# Spring Cloud Gateway Configuration
# Route: Order Service
spring.cloud.gateway.routes[0].id=vtibackend-order-service
# lb:loadbalancer. Thay vì trỏ trực tiếp vào địa chỉ IP cố định, Gateway sẽ tìm dịch vụ có tên order-service từ Service Discovery
spring.cloud.gateway.routes[0].uri=lb://vtibackend-order-service
# Prefix của request
spring.cloud.gateway.routes[0].predicates[0]=Path=/orders/**
# Cắt bỏ 1 phần đầu tiên của đường dẫn (phần /orders)
spring.cloud.gateway.routes[0].filters[0]=StripPrefix=1

# Route: Product Service
spring.cloud.gateway.routes[1].id=promotion-service
spring.cloud.gateway.routes[1].uri=lb://promotion-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/products/**
# Cắt bỏ 1 phần đầu tiên của đường dẫn (phần /products)
spring.cloud.gateway.routes[1].filters[0]=StripPrefix=1

# Logging Configuration
logging.level.root=DEBUG

# Eureka Client Configuration
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

logging.level.org.springframework.cloud.gateway=DEBUG

# Security OAuth2 Resource Server
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/password
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8080/realms/password/protocol/openid-connect/certs