version: '3.8'

services:
  department-service:
    image: ${IMAGE_NAME}:${IMAGE_TAG}
    container_name: department-service
    
    # 1. THÊM BLOCK BUILD: Chỉ đường cho Docker Compose biết chỗ để tự build
    build:
      context: ./orders-service  # <-- CHÚ Ý: Đổi thành tên thư mục con chứa file pom.xml của bạn (ví dụ: orders-service hoặc department-service)
      dockerfile: Dockerfile

    # 2. SỬA DÒNG NÀY: Bảo Docker chỉ pull nếu dưới máy không có sẵn Image
    pull_policy: if_not_present

    ports:
      - '${APP_PORT}:${APP_PORT}'
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - APP_PORT=${APP_PORT}
      - DB_URL=${DB_URL}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    restart: always