server:
  port: 8086

spring:
  application:
    name: promotion-service

  datasource:
    url: jdbc:mysql://localhost:3306/promotionservice?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: "123456789"
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer


  data:
    redis:
      host: localhost
      port: 6379

      timeout: 60000ms


  cache:
    type: redis
    redis:
      time-to-live: 10m
      cache-null-values: false
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: false
    fetch-registry: false